name: Build & Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build static content
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.79.1'
          extended: true
      - name: Build
        run: hugo
      - name: Upload output
        uses: actions/upload-artifact@v1
        with:
          name: public
          path: ./public
  publish:
    name: Publish to chessbr.github.io
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'chessbr/chessbr.github.io'
          token: ${{ secrets.CD_BLOG_TOKEN }}
          path: static-site
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: public
      - name: Apply the update
        shell: bash
        run: |
          cp -r ./public/* ./static-site
      - name: Commit files
        run: |
          cd static-site
          git reset HEAD --hard
          git config --local user.email "support@hess.dev"
          git config --local user.name "GitHub Action - Deploy"
          git add .
          git commit -m "Update blog" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          repository: 'chessbr/chessbr.github.io'
          github_token: ${{ secrets.CD_BLOG_TOKEN }}
          directory: static-site
          force: true
          branch: main
